interpreter = "0.23.4"
packages = [
    "https://cdn.holoviz.org/panel/1.3.0/dist/wheels/bokeh-3.3.0-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/1.3.0/dist/wheels/panel-1.3.0-py3-none-any.whl",
    "pandas", "numpy", "scipy", "matplotlib"]
[files]
"plot.py" = ""
"closed_competitive.py" = ""